---
  # Create two ec2 instance for Nginx webservers
  - hosts: localhost
    connection: local
    gather_facts: false
    user: root
    pre_tasks:
      - include_vars: ~/repos/ansible-lab/roles/provision-ec2-instance/vars/webservers.yml
    roles:
    - provision-ec2-instance
    
  # Provision webserver with Nginx
  - hosts: webservers
    become: yes
    become_user: root
    roles:
    - nginx

  # Create ec2 instance for HAProxy server
  - hosts: localhost
    connection: local
    gather_facts: false
    user: root
    pre_tasks:
      - include_vars: ~/repos/ansible-lab/roles/provision-ec2-instance/vars/loadbalancer.yml
    roles:
    - provision-ec2-instance

  # Provision instance with HAProxy
  - hosts: loadbalancer
    become: yes
    become_user: root
    roles:
    - haproxy